#!/bin/bash

function _gsed() {
    echo "replace $1 with $2";
    grep -IErl $1 . | xargs sed -i '' "s/$1/$2/g"
}
alias grepsed='_gsed'

function _rmpyc() {
    if [ -n "$1" ]; then
        echo "delete pyc in $1/"
        find "$1" -name "*.pyc" -type f -print -delete;
    else
        echo "delete pyc in ./"
        find . -name "*.pyc" -type f -print -delete;
    fi
}
alias rmpyc='_rmpyc'

# if [[ -z "${PYENV_VERSION}" ]]; then
#     function _pip() {
#         [[ -z "${VIRTUAL_ENV}" ]] && [[ "$@" =~ ^"install" ]]\
#             && echo -e "\033[0;38;5;130m"'installing python packages install site.USER_BASE dir'"\033[0;38;5;30m"\
#             && __USER='--user '
#         echo "pip $@ ${__USER}" | $SHELL
#         unset __USER
#     }
#     alias pip=_pip
#     function _pip3() {
#         [[ -z "${VIRTUAL_ENV}" ]] && [[ "$@" =~ ^"install" ]]\
#             && echo -e "\033[0;38;5;130m"'installing python packages install site.USER_BASE dir'"\033[0;38;5;30m"\
#             && __USER='--user '
#         echo "pip3 $@ ${__USER}" | $SHELL
#         unset __USER
#     }
#     alias pip3=_pip3
# fi

# alias mkvirtualenvs='mkvirtualenv --system-site-packages'
# FIXME betterway
alias clearvirtualenv='echo -e "clear:\
    ${VIRTUAL_ENV/#\/Users\/peter\/peter\/eleme\/srv\/virtualenvs\/}";\
    virtualenv --clear ${VIRTUAL_ENV/#\/Users\/peter\/peter\/eleme\/srv\/virtualenvs\/}'

which nvim > /dev/null 2>&1
if [ $? -eq 0 ] ; then
    alias vi=nvim
    alias vim=nvim
fi

alias cdde='cd ~/Desktop'
alias cdwp='cd ~/Desktop/work'
alias cdmp='cd ~/Documents/dev'

