#!/bin/env bash

function extract () {
        if [ -f $1 ] ; then
                case $1 in
                        *.tar.bz2)        tar xjf $1                ;;
                        *.tar.gz)        tar xzf $1                ;;
                        *.bz2)                bunzip2 $1                ;;
                        *.rar)                rar x $1                ;;
                        *.gz)                gunzip $1                ;;
                        *.tar)                tar xf $1                ;;
                        *.tbz2)                tar xjf $1                ;;
                        *.tgz)                tar xzf $1                ;;
                        *.zip)                unzip $1                ;;
                        *.Z)                uncompress $1        ;;
                        *)                        echo "'$1' cannot be extracted via extract()" ;;
                esac
        else
                echo "'$1' is not a valid file"
        fi
}


function psg() {
        if [ ! -z $1 ] ; then
                echo "Grepping for processes matching $1..."
                ps aux | grep $1 | grep -v $1
        else
                echo "!! Need name to grep for"
        fi
}

function proxy_active() {
        export ALL_PROXY=socks5://127.0.0.1:1086
        export http_proxy=http://0.0.0.0:1087;export https_proxy=http://0.0.0.0:1087;
}

function proxy_deactive() {
        unset ALL_PROXY http_proxy https_proxy
}

function cht() {
        echo "change current window title to" $1;
        DISABLE_AUTO_TITLE="true"
        echo -ne "\e]1;$1\a"
}
