#!/bin/bash

# zsh ignore
[[ "${SHELL}" = "/bin/zsh" ]] && return

[ -z "$PS1" ] && return
echo -ne "Good Morning,${USER}!. It's "; date '+%A, %B %-d %Y'
uptime

black="\[\033[0;38;5;0m\]"
red="\[\033[0;38;5;1m\]"
orange="\[\033[0;38;5;130m\]"
green="\[\033[0;38;5;2m\]"
yellow="\[\033[0;38;5;3m\]"
blue="\[\033[0;38;5;4m\]"
bblue="\[\033[0;38;5;12m\]"
magenta="\[\033[0;38;5;55m\]"
cyan="\[\033[0;38;5;6m\]"
white="\[\033[0;38;5;7m\]"
coldblue="\[\033[0;38;5;33m\]"
smoothblue="\[\033[0;38;5;111m\]"
iceblue="\[\033[0;38;5;45m\]"
turqoise="\[\033[0;38;5;50m\]"
smoothgreen="\[\033[0;38;5;42m\]"
othercolor="\[\033[0;38;5;30m\]"

function pre_prompt {
        newPWD="${PWD}"
        host=$(echo -n ${HOSTNAME} | sed -e "s/[\.].*//")
        let promptsize=$(echo -n "┌(${PWD})($(whoami)@$host ddd., DD mmm YY)┐" \
                | wc -c | tr -d " ")

        let fillsize=${COLUMNS}-${promptsize}
        fill=""
        while [ "$fillsize" -gt "0" ]
            do
                fill="${fill}─"
                let fillsize=${fillsize}-2
        done

        if [ "$fillsize" -lt "0" ]
                then
                        let cutt=3-${fillsize}
                        newPWD="...$(echo -n $PWD | sed -e "s/\(^.\{$cutt\}\)\(.*\)/\2/")"
        fi

        unset host
        unset fillsize
        unset promptsize
        unset cutt
}

PROMPT_COMMAND=pre_prompt

case "$TERM" in
    xterm*)
        PS1="${bblue}┌─(${orange}\u@\h \$(date \"+%a, %d %b %y\")${bblue})─\${fill}─(${green}\$newPWD${bblue})\${fill}─\n${bblue}└─(${orange}\$(date \"+%H:%M\") \$${bblue})${othercolor} "
        ;;
    screen*)
        PS1="${bblue}┌─(${orange}\u@\h \$(date \"+%a, %d %b %y\")${bblue})─\${fill}─(${green}\$newPWD${bblue})\${fill}─\n${bblue}└─(${orange}\$(date \"+%H:%M\") \$${bblue})${othercolor} "
        ;;
        *)
        PS1="┌─(\u@\h \$(date \"+%a, %d %b %y\"))─\${fill}─(\$newPWD)\${fill}─\n└─(\$(date \"+%H:%M\") \$) "
        ;;
esac

unset newPWD
unset black
unset red
unset orange
unset green
unset yellow
unset blue
unset bblue
unset magenta
unset cyan
unset white
unset coldblue
unset smoothblue
unset iceblue
unset turqoise
unset smoothgreen
unset othercolor
